# Generated by Django 3.2.25 on 2025-09-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('response', models.TextField()),
                ('confidence', models.FloatField()),
                ('escalated', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='query_images/')),
                ('diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('escalated_to', models.CharField(blank=True, max_length=100, null=True)),
                ('escalation_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
