# Generated by Django 3.2.25 on 2025-09-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerquery',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
