# Generated by Django 3.2.25 on 2025-09-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_farmerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='preferred_crop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='preferred_season',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='language',
            field=models.CharField(default='hi', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
