# Generated by Django 5.2.6 on 2025-09-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20250922_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerquery',
            name='crop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerquery',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerquery',
            name='season',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
